### ISSUE TITLE
fix rails not including images

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/maps#19]
For search bar and info window box

**Comment by basketbaseb** [comment]
should look in /assets/images/ but not working for some reason...
Info window i changed to just a + sign but want to change it to yelp.png

**Comment by natyconnor** [comment]
console output gives:
`ActionController::RoutingError (No route matches [GET] "/assets/images/search.png")`

This is a rails thing. To use asset pipeline, you need to use helper-method:

`background: url(<%= asset_path 'search.png' %>)`

I tried it out on my machine, and it no longer gives the error, but I'm not sure if your image is being loaded right. Looks like it's too big or something.

**Comment by basketbaseb** [comment]
fixed in e5f70bf5c5d0bb2f024db0a495e9ff63850bda4f
