### ISSUE TITLE
Street view remains even after marker is deleted

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/maps#24]

**Comment by basketbaseb** [comment]
Related: after deleting marker from map, hovering over it's pano image pans to the original position of the deleted marker. Should be fixed if we remove the pano image from the image-container.

**Comment by natyconnor** [comment]
Currently I actually keep the markers in the array when deleting them, which is why the map will pan to where the marker was. I would remove it from the array too, but I think it would break something until we get the pano to be removed first.

**Comment by natyconnor** [comment]
Fixed in 468a642fe98a919e8e603a0c3e735897fd39610e
