### ISSUE TITLE
Yelp added features

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/maps#28]
Features:
Zoom into map marker so we see yelp markers more separated.
Clicking on yelp marker displays information about the business.
POSSIBLE rework of image-container, instead of containing street views of markers, it contains the 5 pictures of the yelp businesses. Hovering over those pictures animates the associated yelp markers.

**Comment by basketbaseb** [comment]
added in zoom feature in cc3f5a0328f07988d4ecb384a1b61d6799744330

**Comment by basketbaseb** [comment]
For image-container, instead of overwriting what's already there, maybe create a new yelp-container that is absolutely positioned over the image-container that appears when yelp markers are created.

**Comment by natyconnor** [comment]
Would be nicer if zoom was based on max distance between markers. If you're in a sparse location, sometimes the zoom in is too much and you don't see all the markers. Or even a small screen may cut off some of them. 

Might also pan map to center of all markers, not just to where clicked marker is.

**Comment by basketbaseb** [comment]
added business' info in yelp marker info window in a05b114c55b45173d9ad9f1f9ad574c9766f9e8e

**Comment by basketbaseb** [comment]
noticed map will zoom and pan even if there aren't any yelp businesses found. This will be fixed once I add the zoom to max distance between markers feature.

**Comment by basketbaseb** [comment]
fixed zoom to fit yelp markers in map bounds in f5582b480a33b34dc47ca1f91afc3b0147f543fa

**Comment by basketbaseb** [comment]
new feature: reviews in yelp info window.

**Comment by basketbaseb** [comment]
added in 0f813795fb0f4ac39cb881e7f4f6ac77af1d4f9c

**Comment by basketbaseb** [comment]
closing this issue. Will make new issue as new features arise.
